# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmeu4-Ny6FlHh8UqBHJq4MhiG14awQPQ
"""

if __name__ == "__main__":
    
    if len(sys.argv) >= 1:

        get_info_parameters()
            
        
    elif len(sys.argv) == 0:
        
        how_to_use()
        
    else:
        
        pass